### ISSUE TITLE
3.0

### ISSUE THREAD

**Issue by jmamma** [jmamma/MIDICtrl20_MegaCommand#110] opened 2020-04-01 10:10 UTC
- [x] New project spec. Increase parameter locks to 8 or revise parameter locks completely
~- [ ] Drop support for A4/EXT tracks.~
- [x] Project format conversion.
- [x] Add proper MIDI machine support. 
- [ ] WAV editor
- [ ] Improve WAV designer.
- [ ] Advanced sampling functionalities. 
- [x] Track resolutions to match MD. Add half speed as well.
- [ ] Multitimberal poly mode. 

@yatli thoughts?

**Comment by yatli** [comment] 2020-04-01 22:15
- Double (or custom) step resolution for MD
- Automation tracks in the grid
- Piano roll for MIDI machines? :x
- Multiple POLY groups

**Comment by yatli** [comment] 2020-04-01 22:24
Wrt the project format:

- Self-descriptive metadata: DEVICE={MD|MM|A4|OT|...}, PRJVER=3.0, TRKSIZE=..., TRKCNT=...
- Sample assignment info for a project. On loading a project, prompt to sync the samples.

**Comment by yatli** [comment] 2020-04-01 22:30
Wrt A4/EXT/MM/whatsover support:

Initially we can simply drop the A4/EXT support.
If we could have a hardware abstraction layer, and later on if any of us feel like developing for a new machine, we can create multiple build profiles, mix-and-match the relevant pages.

I'm good with one-MC-per-machine. UART1=control the machine. UART2=interconnection.

**Comment by jmamma** [comment] 2020-04-02 01:37
Regarding poly groups. Perhaps each grid slot should be assignable to a group.


> * Self-descriptive metadata: DEVICE={MD|MM|A4|OT|...}, PRJVER=3.0, TRKSIZE=..., TRKCNT=...
> 
> * Sample assignment info for a project. On loading a project, prompt to sync the samples.

This can be built in to the project header class.

https://github.com/jmamma/MIDICtrl20_MegaCommand/blob/master/avr/cores/megacommand/MCL/Project.h

**Comment by jmamma** [comment] 2020-04-02 03:49
Automation tracks in the grid <- what did you have in mind @yatli

**Comment by yatli** [comment] 2020-04-02 07:38
> Automation tracks in the grid

RAM machine actions, LFO patterns + enable/disable etc.
Master FX automation
Tempo change events?

**Comment by jmamma** [comment] 2020-04-03 01:30
Should we have an underlay grid for this ?

**Comment by jmamma** [comment] 2020-07-29 09:22
@yatli Looks like I want to keep the A4/Ext support going forward...

I am going to re-work the ExtSeq page.

Display the 4 notes on screen.

I want to abstract away the "on-off" sequencer by adding a length control knob for notes.
And also, allow for the ability to control each note value from the MC. (Currently you need to enter notes from and ext midi device)

@yatli any thoughts on a clever UI for adjusting notes and note length simultaneously. 4 notes per step etc...

**Comment by yatli** [comment] 2020-07-29 09:28
Any chance we also support MnM? :p

**Comment by yatli** [comment] 2020-07-29 09:34
I've actually been thinking about a new sequencer for a while.
The sequencer has to be friendly with the trig interface while maintaining both note trigs and lock trigs.
I suggest we decouple note editing and lock editing. In this way, we reuse the step sequencer UI for locks, but do notes with a new UI.

**Comment by jmamma** [comment] 2020-07-29 09:38
> I suggest we decouple note editing and lock editing

Can you elaborate a bit ?

--

Also, I almost forgot, I already pre-allocated space for parameter locks in ExtSeqTrack.h so we could implement locks right away without changing project spec.

**Comment by yatli** [comment] 2020-07-29 10:02
> Can you elaborate a bit ?

On MnM there are 3 types of trigs: AMP, FILTER, LFO.
Basically, ALL=what we have on MD, and each component controls certain page of parameters.

When we decouple note editing from lock editing, we effectively separate the note page from the others.
The note page contain parameters like note1~4, length, slide etc, and we can choose a different UI layout (e.g. no need to display knobs for notes)

And the other parameters can be locked in the Elektron style.

**Comment by yatli** [comment] 2020-07-29 10:29
![image](https://user-images.githubusercontent.com/20684720/88789449-5735d980-d1c9-11ea-90aa-b0056b09cfc0.png)

Could fit 11 notes vertically + 2 overflow/underflow indicators

**Comment by jmamma** [comment] 2020-07-29 10:33
Are you thinking piano roll ?

or are you suggesting increase polyphony beyond 4 notes?

**Comment by yatli** [comment] 2020-07-29 11:24
yep piano roll thingy, but designed for compact screen.

My favorite design is the Reason matrix step sequencer emulating LCD display:

![image](https://user-images.githubusercontent.com/20684720/88794489-222d8500-d1d1-11ea-923f-fce9e1e56564.png)

On the left there's a multi switch to control currently displayed octave. We could use a knob to control that, one octave at a time.

**Comment by jmamma** [comment] 2020-07-29 11:29
MATRIX sequencer. brings back memories. 

Yeah we can do piano roll. does this mean we need a cursor for selecting notes?

**Comment by yatli** [comment] 2020-07-29 11:31
The TI leds can be used as a vertical projection of the display. so each note is displayed as a consecutive range on the TI.
Pressing a trig selects the notes that are covered in the range.
If ambiguity presents, then select the notes whose heads are nearest to the pressed trig.

**Comment by jmamma** [comment] 2020-07-29 11:34
how do we select individual notes in a chord?
for instance if we want to shift or lengthen a note

**Comment by yatli** [comment] 2020-07-29 11:35
MD arrow keys?

**Comment by yatli** [comment] 2020-07-29 11:38
Or we need to use a knob to indicate "selection"

**Comment by jmamma** [comment] 2020-07-29 11:38
i guess we could also use an encoder for that.

enc -> note select
enc -> horizontal shift
enc -> vertical shift
enc -> zoom ? 

we also need micro timing and conditional encoders.

and pattern length.

**Comment by yatli** [comment] 2020-07-29 11:41
> enc -> zoom ?

I think we probably don't need zoom.
Vertical scroll instead?

**Comment by jmamma** [comment] 2020-07-29 11:43
we dont need micro timing exactly.. if we have sufficient horizontal resolution we can represent utiming by shifts in start/end position of notes.

horizontal zoom might be useful here

**Comment by yatli** [comment] 2020-07-29 11:46
> horizontal zoom might be useful here

Ah ok I see. A combination of horizontal zoom and "snap to the grid", because the display has the fixed resolution to show 16 segments.
Can be put in the menu?

**Comment by yatli** [comment] 2020-07-29 12:01
Another option is to go modal. Let there be two modes, INSERT/SELECT, where the trigs behave as:

INSERT mode: 4 encoders bound to note pitch. Press trig toggles notes. Press and hold a trig edits pitch.
SELECT mode: 4 encoders bound to H/V shifting, length and expression (expression can be velocity, accent, porta etc.) Press trig toggles selection (in case of a chord, cycles through the notes). Press and hold go into temporary pitch editing.

**Comment by jmamma** [comment] 2020-07-29 12:03
yeah, pretty much what i was thinking. you have 2 sets of encoders. the second set relating to note position + selection is swapped in when you hold a trig.

**Comment by yatli** [comment] 2020-07-29 12:03
If done right, I feel this could form the basis of a great sequencer product...
The Elektron interface is nice, but not good enough for chords or strummings

**Comment by jmamma** [comment] 2020-07-29 12:06
We already beat the elektron sequencer, because the on+off sequencer design inherently supports legato (recording of note overlap) :D

**Comment by jmamma** [comment] 2020-07-29 12:07
just need to wrap it up in a better UI.

**Comment by yatli** [comment] 2020-07-29 12:10
One thing I love most about the FL Studio PR is its ability to click on one note to copy all its properties (length, velocity etc.) and then apply them to newly drawn notes.

This can apply to the INSERT mode, where you long press a chord and capture its properties. You don't need to repeatedly adjust length/chord for the newly toggled trigs.

**Comment by jmamma** [comment] 2020-07-29 12:33
Sounds good to me.

**Comment by yatli** [comment] 2020-07-29 12:35
(Talks about Reason and FL Studio buh buh)
So why do I end up staying with Bitwig Studio (

**Comment by jmamma** [comment] 2020-07-29 12:37
been meaning to download bitwig again. i've been slowly catching up on DAW + DSP + VST tech, since I left off 2-3 years ago? Lots to play with.

**Comment by jmamma** [comment] 2020-07-29 12:38
**Ext Sequencer Refresh Tutorial (Lesson 1):**

```
 34 class ExtSeqTrackData {
 35 public:
 36   uint8_t length;
 37   uint8_t speed; // Resolution = 2 / ExtPatternResolution
 38   uint8_t reserved[NUM_EXT_NOTES];
 39   int8_t notes[NUM_EXT_NOTES][NUM_EXT_STEPS]; // 128 steps, up to 4 notes per step
 40   uint8_t locks[NUM_EXT_LOCKS][NUM_EXT_STEPS]; 
 41   uint8_t locks_params[NUM_EXT_LOCKS];
 42   uint64_t lock_masks[NUM_EXT_LOCKS];
 43 
 44   uint8_t conditional[NUM_EXT_STEPS];
 45   uint8_t timing[NUM_EXT_STEPS];
 46 };
```

The Ext Seq uses an on+off approach. Each step can have up to 4 notes of different pitch, with a state in either NULL, ON or OFF. 

The on+off design has some drawbacks. Namely consecutive short notes.
By design, note on events cannot be placed on the same step as note off events of the same pitch. In order to play consecutive  16th notes of the same pitch we need to double the sequencer resolution as illustrated below.

```
1 .            2.           3.           4.

[           ] [           ] [           ] [            ]   1x 
ON              OFF           ON            OFF

[     ][     ][     ][     ][     ][     ][     ][     ]  2x
ON     OFF     ON     OFF   ON     OFF    ON     OFF
```

An alternative design would be to increase the polyphony to 8. and allow on + off  for the same pitch on the same step. This would consume the same amount of RAM, but be limited to 64 steps. Perhaps this would have been more lucrative as you gain additional polyphony. The drawback being, you would lose polyphony if playing consecutive notes quickly and additional processing overhead, as note array lengths double from 4 to 8 for each step.

The other design approach was to have uint8_t per note representing note length. This would also consume the same amount of RAM at 64 steps, but would require processing overhead to keep track of when to turn notes off.

**Comment by jmamma** [comment] 2020-07-29 12:48
Originally I had attempted to conceal the doubling of resolution, by halving displayed track length and doubling the cur_step cursor speed.

This is evident in my selection of:
```
 42   uint64_t lock_masks[NUM_EXT_LOCKS];
```

Where locks patterns were only intended to only be 64 steps in length...

**Comment by jmamma** [comment] 2020-07-29 12:50
sleep time 🌔

**Comment by yatli** [comment] 2020-07-29 14:18
Good night.

**Comment by yatli** [comment] 2020-08-10 05:04
https://github.com/jmamma/MIDICtrl20_MegaCommand/pull/128

**Comment by yatli** [comment] 2020-11-23 12:53
@jmamma is the latest `dev` working? I'm trying to build it from Linux but it doesn't respond after upload.

**Comment by jmamma** [comment] 2020-11-23 13:00
dev branch is working.

If DEBUG_MODE is enabled, the sketch will be too large. Need to disable DEBUG_PRINT_FN()

**Comment by yatli** [comment] 2020-11-23 13:03
Check out https://github.com/jmamma/MIDICtrl20_MegaCommand/commit/7030e3a19908ad722ec819c8fb49984d617da578

Now you can do `make debug_upload -j` :D

**Comment by jmamma** [comment] 2020-11-23 13:04
I saw. good work!

mcl_setup.cpp <- #ifdef MCL  
is probably the issue.

can you fix?

**Comment by yatli** [comment] 2020-11-23 13:06
Disabled DEBUG_PRINT_FN, sketch size is: `avrdude: 238422 bytes of flash written`
Nothing coming out from the serial monitor.

**Comment by yatli** [comment] 2020-11-23 13:09
> mcl_setup.cpp <- #ifdef MCL

Oh I see. This one again. I'll fix it

**Comment by yatli** [comment] 2020-11-23 13:13
Got these:

```
/usr/bin/avr-ld: /tmp/main.elf.OXOu1f.ltrans0.ltrans.o: in function `MCLSeq::seq()':
/home/yatli/git/MIDICtrl20_MegaCommand/avr/cores/megacommand/MCL/MCLSeq.cpp:174: undefined reference to `SeqTrack::send_slides(unsigned char volatile*, unsigned char)'
/usr/bin/avr-ld: /home/yatli/git/MIDICtrl20_MegaCommand/avr/cores/megacommand/MCL/MCLSeq.cpp:174: undefined reference to `SeqTrack::send_slides(unsigned char volatile*, unsigned char)'
/usr/bin/avr-ld: /home/yatli/git/MIDICtrl20_MegaCommand/avr/cores/megacommand/MCL/MCLSeq.cpp:174: undefined reference to `SeqTrack::prepare_slide(unsigned char, int, int, signed char, signed char)'
/usr/bin/avr-ld: /home/yatli/git/MIDICtrl20_MegaCommand/avr/cores/megacommand/MCL/MCLSeq.cpp:174: undefined reference to `SeqTrack::prepare_slide(unsigned char, int, int, signed char, signed char)'
```

**Comment by jmamma** [comment] 2020-11-23 13:32
Thanks. forgot to check-in.

It's there now.

**Comment by yatli** [comment] 2020-11-23 13:33
yatli cold-booting back...

**Comment by jmamma** [comment] 2020-11-23 13:36
enjoy the piano-roll + automation editor 😁

**Comment by yatli** [comment] 2020-11-23 13:53
Press SAVE+WRITE then release: goes into Load Project.
Then press SAVE: goes back to global menu, but freezes.

**Comment by jmamma** [comment] 2020-11-23 13:59
nope.

shouldn't do that. no changes made there.

SAVE+WRITE opens up global settings for me.

**Comment by jmamma** [comment] 2020-11-23 14:02
avrdude: writing flash (241858 bytes):

make debug_upload -j -> binary is too big ?

should be:

avrdude: writing flash (226054 bytes):

**Comment by jmamma** [comment] 2020-11-23 14:07
Don't know why ```make debug_upload -j``` is resulting in a larger binary size?

make_and_upload.sh is working okay.

..

getting late here. i'm off

**Comment by yatli** [comment] 2020-11-23 14:08
catch you later. going home now :)

**Comment by jmamma** [comment] 2020-11-24 01:13
```
125 debug: CXXFLAGS += -DDEBUGMODE=1
126 debug: CFLAGS += -DDEBUGMODE=1
127 debug: main.hex
128 
129 debug_upload: debug upload
```

The reason the file size is 241858 is because DEBUG_MODE is enabled. 
The weird behaviour your were seeing is due to program corruption because the ROM size is too big.
Initially I thought this was the 8KB issue, but it looks like there is an additional problem when we hit 240KB ... 

If compiling with DEBUG_MODE need to disable PRINT_FN() to save a few KB.

**Comment by yatli** [comment] 2020-11-24 08:33
Guess what:

```
avr-gcc 10.2
   text    data     bss     dec     hex filename
 231286    6306   42409  280001   445c1 main.elf

avr-gcc 9.3
   text    data     bss     dec     hex filename
 230980    6088   42409  279477   443b5 main.elf

avr-gcc 8.3
   text    data     bss     dec     hex filename
 217344    6014   42409  265767   40e27 main.elf
```

Bigger is better (TM)

**Comment by jmamma** [comment] 2020-11-24 08:36
counterintuitive 

wonder if the optimisation options have changed.

**Comment by jmamma** [comment] 2020-11-24 08:37
https://www.avrfreaks.net/forum/code-size-gets-bigger-each-new-version-gcc

**Comment by yatli** [comment] 2020-11-24 08:37
lol

**Comment by yatli** [comment] 2020-11-24 10:16
The only compiler that works here is the one installed from arduino-cli (7.3-atmel-3.6.1-arduino)

**Comment by jmamma** [comment] 2020-11-24 10:29
what do you mean 'works'?

**Comment by yatli** [comment] 2020-11-24 10:46
Using 7.3 = fully working FW
Using 8.3+  = all kinds of aforementioned glitches

**Comment by jmamma** [comment] 2020-11-24 10:51
```all kinds of aforementioned glitches```

wouldn't even know where to begin trying to diagnose that one

**Comment by yatli** [comment] 2020-11-24 10:52
Or could it be `avr-libc` archlinux package? All the 8.3+ compilers are using the same libc package.

**Comment by jmamma** [comment] 2020-11-24 11:00
I'm seeing firmware glitches when we get to around 240KB. Corrupt strings and glyphs.

Perhaps there is a problem in the way progmem is being laid out.

**Comment by yatli** [comment] 2020-11-24 11:26
https://github.com/arduino/toolchain-avr

^^^ The Arduino hacks applied to the compiler and libc etc.

**Comment by jmamma** [comment] 2020-11-24 11:31
good find. now we know. 

is it worth pursuing the newer versions?

**Comment by yatli** [comment] 2020-11-24 11:38
Short answer, no :D

Higher version = more code bloat.

**Comment by jmamma** [comment] 2020-11-24 11:45
Revised Todo for 3.0:

Low Hanging:

- [x] Save Poly Settings along with Route slot
- [x] Save LFO in dedicated LFO slot
- [x] Add probability menu option to Piano Roll (just need to copy the Velocity implementation)
- [x] Rename Chain to Load
- [x] Expand Group Select options, ~add vertical divider to show Grid A and Grid B groups.~

Medium:

- [x] Fix grid device mapping and Ext Track saving
- [ ] MIDI Port device select. 
- [ ] Refactor ARP code to be sequence track + ext support.
- [ ] MD Exit command. We need a single sysex command to exit all auxiliary modes on the MD (record/edit/mute etc). This is to be executed when the trig interface is active.
- [ ] Fix WavDesigner GUI. Add shift menu for Oscillator + Waveform selection.
   

Hard:

- [ ] Project Conversion
- [ ] MNM support tested.

Stretch:

- [ ] Circle round to Sample Mangagemnt/Wav editor. I can't remember how far we got?

Conceptual:

- [ ] Make sure we are satisfied with the new Project and Track Layouts for 3.0

**Comment by jmamma** [comment] 2020-11-24 11:54
Above is the revised todo list. Rough goal is to get 3.0 out before the year's end.

**Comment by yatli** [comment] 2020-11-24 12:07
>  Circle round to Sample Mangagemnt/Wav editor. I can't remember how far we got?

- ✅ wav MC->MD
- 🚧 sds MD->MC
- ✅ MD ROM slot query
- ❓ MD ROM slot copy/paste/delete
- ✅ revised wav file reader for accessing custom chunks
- ✅ wav loop points <-> SDS loop points conversion. It Just Works (tm)
- 😱 MD RAM slot copy to ROM
- 😱 MD RAM direct access

**Comment by yatli** [comment] 2020-11-24 12:08
> MD RAM direct access

Oh I remember that I made a decompiler for this.

**Comment by jmamma** [comment] 2020-11-27 07:38
Any idea why saving A4 tracks is so slow. something up with the device driver?

**Comment by jmamma** [comment] 2020-11-27 07:50
Fixed: 3c2bb638d814ce98d9ea489b45fa4e484dc262bf

You may want to improve ^

**Comment by jmamma** [comment] 2020-11-27 07:58
GenericMidiDevice track saving is working correctly now. 

Grid B: Tracks 5-6 are GM for the A4.

--

We could add a device select option for port 2. currently it scans through A4, and MNM probes before falling back to GenericMidi

**Comment by jmamma** [comment] 2020-11-27 08:03
@yatli can you test MNM. people of elektronauts have been asking about it.

**Comment by yatli** [comment] 2020-11-27 12:12
Can do. I'll bring my MNM on site next week.

**Comment by jmamma** [comment] 2020-11-27 12:23
LFO now saved in grid..

**Comment by jmamma** [comment] 2020-11-27 15:03
improved group select. 🛌  time.

**Comment by jmamma** [comment] 2020-11-30 07:25
```
 41 void LoadProjectPage::on_delete(const char *entry) {
 42   file.open(entry, O_READ);
 43   bool dir = file.isDirectory();
 44   if (dir) {
 45     if (SD.chdir(entry)) {
 46       SD.vwd()->rmRfStar(); //Too much progmem
 47       _cd_up();
 48     } 
 49   } 
 50   file.close();
 51 } 
```

I had to implement the use of rm -rf to delete project directory.
the _cd_up(); 
or SD.chdir("/Project/"); 

doesn't work after the delete. And i'm stuck in an empty DIR.

Any suggestions?

**Comment by yatli** [comment] 2020-11-30 07:45
You're holding a FILE reference to a deleted entry.
Maybe close it before deleting?
Also, we don't really need the full rm -rf * semantic -- the project dir is not recursive. So maybe just foreach then delete, close the dir file object, then delete the dir?

**Comment by jmamma** [comment] 2020-11-30 11:11
Closing the file fixed it.

241420 (itterative)
vs
241696 (rm -rf *)

**Comment by jmamma** [comment] 2020-11-30 12:25
95d96a1

Project Conversion:

- [x] load old project
- [x] check version
- [x] initialise new project using old project name.
- [x] iterate over Tracks
- [x] convert MD Tracks
- [x] convert A4/Ext Tracks

**Comment by jmamma** [comment] 2020-12-01 06:45
All the conversion routines are done. Untested.

**Comment by jmamma** [comment] 2020-12-01 06:47
Wastes around 3KB. we can drop this functionality in  a later release.

**Comment by yatli** [comment] 2020-12-01 06:53
Waaa that's fast

**Comment by jmamma** [comment] 2020-12-01 10:00
Converted project is populated with slots, but  I get a lock up on slot load.

**Comment by jmamma** [comment] 2020-12-01 10:44
MDSeqTrack::set_length() locks up when length = 0;

So something not right with saving/loading of track length.

**Comment by jmamma** [comment] 2020-12-01 10:49
Looks like a problem with saving... after/during MDTrack::convert.

**Comment by jmamma** [comment] 2020-12-01 11:10
MD sequencer side of the conversion is working.

Some reason, MDRouteTrack is being loaded, when the slot should be empty.

**Comment by jmamma** [comment] 2020-12-01 11:23
couldn't replicate on reboot.. wonder why.

--

some small issue with locks on MD side. will need to work through it.

**Comment by jmamma** [comment] 2020-12-01 13:18
0353fb6

Tentative fix for accidently loading EMPTY_TRACK_TYPES.

I seemed to have traced it to the fact that empty tracks are converted to their respective track type when cached in RAM. The 'active = EMPTY' status is lost in the process.

**Comment by jmamma** [comment] 2020-12-01 13:19
MD conversion seems good.

A4/EXT is broken. Some note data in the piano role but I'm not hearing anything.. The sound conversion looks okay, at first glance.

**Comment by jmamma** [comment] 2020-12-01 13:19
🛏️ time

**Comment by jmamma** [comment] 2020-12-02 05:19
@yatli Ext/A4 conversion done working.

The sound data is a little broken. 2nd oscillator pitch and fine tune are shifted down 1 value. Maybe more values are affected?

I was thinking last night. We don't exactly need the A4Sound decoding for automation as everything is using CCs. I'm wondering if we disable it to save space?

**Comment by jmamma** [comment] 2020-12-02 10:44
@yatli 

~i'm seeing weird behaviour now. above 240K (with debug)~

SDCard error trying to read row 255. getRow() was returning 255 event though gridpage showing row = 86.

False alarm: corrupt chain data causing cache of row 255.

**Comment by jmamma** [comment] 2020-12-02 11:11
```
 62 void A4Sound::convert(A4Sound_270* old) {
 63   // legacy payload len = 398
 64   uint8_t* payload = old->payload;
 65   // skip the partial header 
 66   payload += 6;
 67   // getting data from old payload.
 68   ElektronSysexDecoder decoder(payload);
 69   fromSysex_impl(&decoder);
 70 }
```

Can we verify this payload offset is correct?

**Comment by yatli** [comment] 2020-12-04 06:06
@jmamma conv page garbled text gone after d3967bb1734402bc198067964ed53e7c82322819

**Comment by yatli** [comment] 2020-12-04 06:08
> Can we verify this payload offset is correct?

I fixed sound conversion a while ago, should be OK.

**Comment by jmamma** [comment] 2020-12-04 11:52
Nope, conversion is broken from legacy A4Track->sound

**Comment by yatli** [comment] 2020-12-04 16:40
> I was thinking last night. We don't exactly need the A4Sound decoding for automation as everything is using CCs. I'm wondering if we disable it to save space?

I suspect this won't save us a lot of PROGMEM because we aren't inspecting the fields, and the serializer/deserializer just treats `a4sound_t` as a blob.

I'll make sure to fix this one when I've got time.

**Comment by jmamma** [comment] 2020-12-09 05:00
@yatli can you check the status on MNM integration ?

**Comment by yatli** [comment] 2020-12-09 05:09
From my previous rush:

- Kit encoding/decoding works
- All machines correctly map in the grid
- GRID2 tracks send midi to MNM fine

Need to confirm:

- The new piano roll works with MNM
- Direct kit workspace access works as intended

**Comment by yatli** [comment] 2020-12-09 05:14
Can we use A4/MNM midi keyboard in the piano roll?

**Comment by jmamma** [comment] 2020-12-09 05:18
A4 keyboard works, you need to disable internal sound trigger. 
A4 settings for MCL are in the MCL manual.

**Comment by yatli** [comment] 2020-12-09 05:34
I don't think it'll make a difference if I set the keyboard to INT+EXT vs. EXT for midi in notes?
Pressing the A4 keyboard doesn't seem to change the pitch of the cursor in the PR

**Comment by jmamma** [comment] 2020-12-09 05:35
Make sure MD CTRL Chan is set to INT.

**Comment by jmamma** [comment] 2020-12-09 12:07
Any luck?

**Comment by yatli** [comment] 2020-12-09 13:24
No time to touch the setup today T.T

**Comment by jmamma** [comment] 2020-12-20 12:28
@yatli  Is there anything we're forgetting for the release?

**Comment by yatli** [comment] 2020-12-20 12:37
Program size now?

**Comment by yatli** [comment] 2020-12-20 12:38
Can't think of anything else at the moment.

**Comment by jmamma** [comment] 2020-12-20 12:40
avrdude: 228858 bytes of flash written

**Comment by jmamma** [comment] 2020-12-20 12:50
10minutes to go, and then i'm on vacation.

**Comment by jmamma** [comment] 2020-12-20 13:01
Just in time 

https://github.com/jmamma/MIDICtrl20_MegaCommand/releases/tag/3.00

**Comment by jmamma** [comment] 2020-12-20 13:14
```
$ git diff --stat 4ddbdc2 | grep changed
 363 files changed, 15745 insertions(+), 63194 deletions(-)
```

commit 4ddbdc24810a04ee93234213cde4ca1deb016277 (tag: 2.70)

**Comment by jmamma** [comment] 2020-12-20 13:19
commit 4ddbdc24810a04ee93234213cde4ca1deb016277 (tag: 2.70)
Merge: 2b0e0736 edc7d878
Author: Justin Mammarella <jmamma@gmail.com>
Date:   **Sun Jun 21 11:51:07 2020 +1000**

^ 6 month release cycle. like clockwork.

**Comment by jmamma** [comment] 2020-12-26 04:56
Bit of a chunky increase in progmem after patching  rename() for projects.

264a9514b2a2695d57cdd3ef6b081e947b21970f

avrdude: 229692 bytes of flash written

**Comment by yatli** [comment] 2020-12-26 09:06
Feel like we need an interpreter soon or later. Can we classify our code into timing-critical and glue code?
The ability to script doesn't necessarily mean we execute 100% scripts -- scripts can call into native and vice versa.

**Comment by jmamma** [comment] 2020-12-26 09:08
I reckon there is still room for compression. Offloading to the SDCard feels like desperation .

**Comment by jmamma** [comment] 2020-12-26 09:10
```The word reckon is an [Australian] synonym for think, but is only used for asking for opinion about something. You’re going to hear a lot of Aussies using this word in every day conversation.```

**Comment by yatli** [comment] 2020-12-26 09:13
Alright I learn a new word :)

The thing is, utilizing an interpreter doesn't necessarily mean offloading.
We can compile the script into bytecode and put it in PROGMEM.

**Comment by jmamma** [comment] 2020-12-26 09:15
sure, but what advantage would we gain by doing that ?

**Comment by yatli** [comment] 2020-12-26 09:16
Use some 2K PROGMEM, and implement a highly space-efficient stack machine.
So anything we don't care about the speed, we compile to that target instead of AVR.

**Comment by yatli** [comment] 2020-12-26 09:31
I just don't know how efficient the theoretical machine would be...

**Closed as completed** 2021-03-24 13:15 UTC
